import Navbar from '../../components/layout/Navbar';
import Newsletter from '../../components/layout/Footer';
import LegalContent from './privacy/LegalContent';

const intro = "ZUP! ('we,' 'our,' or 'us') is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by ZUP!. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.";

const sections = [
  {
    heading: "Definitions and key terms",
    paragraphs: ["To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as  -Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.  -Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to S.C. ZUP TRANSPORT S.R.L., (Bulevardul Republicii 4 Piatra Neamț, Județul Neamț) that is responsible for your information under this Privacy Policy. -Country: where ZUP! or the owners/founders of ZUP! are based, in this case is Romania -Customer: refers to the company, organization or person that signs up to use the ZUP! Service to manage the relationships with your consumers or service users. -Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit ZUP! and use the services. -IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet. -Personnel: refers to those individuals who are employed by ZUP! or are under contract to perform a service on behalf of one of the parties. -Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person. -Service: refers to the service provided by ZUP! as described in the relative terms (if available) and on this platform. -Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. -Website: ZUP!’s site, which can be accessed via this URL: www.zup.digital -You: a person or entity that is registered with ZUP! to use the Services."]
  },
  {
    heading: "Information automatically collected",
    paragraphs: ["There is some information like your Internet Protocol (IP) address and/or browser and device characteristics — is collected automatically when you visit our platform. This information may be used to connect your computer to the Internet. Other information collected automatically could be a login, e-mail address, password, computer and connection information such as browser plug-in types and versions and time zone setting, operating systems and platforms, purchase history, (we sometimes aggregate with similar information from other Users), the full Uniform Resource Locator (URL) clickstream to, through and from our Website that may include date and time; cookie number; parts of the site you viewed or searched for; and the phone number you used to call our Customer Services. We may also use browser data such as cookies, Flash cookies (also known as Flash Local Shared Objects) or similar data on certain parts of our Website for fraud prevention and other purposes. During your visits, we may use software tools such as JavaScript to measure and collect session information including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page. We may also collect technical information to help us identify your device for fraud prevention and diagnostic purposes."]

  },
  {
    heading: "Personnel",
    paragraphs: ["If you are a ZUP! worker or applicant, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion."]

  },
  {
    heading: "Sale of Business",
    paragraphs: ["We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of ZUP! or any of its Corporate Affiliates (as defined herein), or that portion of ZUP! or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy."]

  },
  {
    heading: "Affiliates",
    paragraphs: ["We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, 'Corporate Affiliate' means any person or entity which directly or indirectly controls, is controlled by or is under common control with ZUP!, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy."]
  },
  {
    headiing: "Governing Law",
    paragraphs: ["This Privacy Policy is governed by the laws of Romania without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.The laws of Romania, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the website may also be subject to other local, state, national, or international laws.By using ZUP! or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes."]

  },
  {
    heading: "Blocking and disabling cookies and similar technologies",
    paragraphs: ["Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu for more information."]
  },
  {
    heading: "Kids' Privacy",
    paragraphs: ["We do not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers."]
  },
  {
    heading: "Changes To Our Privacy Policy",
    paragraphs: ["We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated Privacy Policy, you can delete your account."]
  },
  {
    heading: "Third-Party Services",
    paragraphs: ["We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ('Third- Party Services').You acknowledge and agree that ZUP! shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. ZUP! does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions."]
  },
  {
    heading: "Tracking Technologies",
    paragraphs: ["We use 'Sessions' to identify the areas of our platform that you havevisited. A Session is a small piece of data stored on your computer or mobiledevice by your web browser."]
  }
  // Add all other sections from your screenshots here in the same format
  // Example for a new section:
  // {
  //   heading: "Sale of Business",
  //   paragraphs: ["We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer... (Your full text here)"]
  // }
];


export default function DispatchPrivacy() {
  return (
    <>
      <Navbar />
      <LegalContent title="Privacy Policy" introduction={intro} sections={sections} />
      <Newsletter />
    </>
  );
}